version: "3"

services:
  ksana-rental:
    platform: linux/amd64
    env_file:
      - ./envfile
    environment:
      - TZ=Asia/Hong_Kong
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: "annangan1111/ksana-rental"
    restart: always
    ports:
      - "3000:3000"
  postgres:
    image: "postgres:17"
    env_file:
      - ./envfile
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
